/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanager.view;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import librarymanager.Files;
import librarymanager.Partner;

/**
 *
 * @author nacho
 */
public class PartnerEdit extends javax.swing.JFrame {

    /**
     * Creates new form EditSocioWindow
     * @param name
     * @param lastname
     * @param dni
     * @param address
     * @param numPartner
     */
    public PartnerEdit(String name, String lastname, String dni, String address, String numPartner) {
        
        initComponents();
        this.editNameInput.setText(name);
        this.editLastnameInput.setText(lastname);
        this.editDniInput.setText(dni);
        this.editAddressInput.setText(address);
        this.editNumSocioInput.setText(numPartner);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editNameLabel = new javax.swing.JLabel();
        editNameInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editLastnameInput = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        editDniInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        editNumSocioInput = new javax.swing.JTextField();
        editAcceptButton = new javax.swing.JToggleButton();
        editCancelButton = new javax.swing.JToggleButton();
        editAddressInput = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar socio");
        setType(java.awt.Window.Type.UTILITY);

        editNameLabel.setText("Nombre");

        jLabel3.setText("Nro Socio");

        Apellido.setText("Apellido");

        editDniInput.setEditable(false);

        jLabel5.setText("DNI");

        editNumSocioInput.setEditable(false);
        editNumSocioInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNumSocioInputActionPerformed(evt);
            }
        });

        editAcceptButton.setText("Aceptar");
        editAcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAcceptButtonActionPerformed(evt);
            }
        });

        editCancelButton.setText("Cancelar");
        editCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCancelButtonActionPerformed(evt);
            }
        });

        addressLabel.setText("Direccion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(editNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(editNameLabel)
                                        .addComponent(editDniInput, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(editNumSocioInput, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Apellido)
                                        .addComponent(editLastnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(editAddressInput))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(editAcceptButton)
                        .addGap(93, 93, 93)
                        .addComponent(editCancelButton)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Apellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editLastnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editDniInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editNumSocioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCancelButton)
                    .addComponent(editAcceptButton))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editNumSocioInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNumSocioInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNumSocioInputActionPerformed

    private void editCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_editCancelButtonActionPerformed

    private void editAcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAcceptButtonActionPerformed
        // TODO add your handling code here:
        Files fileSocio = new Files("partners");
        List <Partner> partners;
        Partner partner;
        try {
            partners = new ArrayList<>(fileSocio.readFile("partners"));
            for(int i = 0; i < partners.size(); i++){
                if(partners.get(i).search(editDniInput.getText()) != null){
                    partner = partners.get(i);
                    
                    if(!" ".equals(editNameInput.getText()) && !" ".equals(editLastnameInput.getText()) &&
                       !" ".equals(editDniInput.getText()) && !" ".equals(editNumSocioInput.getText())  &&
                       !" ".equals(editAddressInput.getText())){
                        partner.setName(editNameInput.getText());
                        partner.setLastname(editLastnameInput.getText());
                        partner.setDni(editDniInput.getText());
                        partner.setAddress(editAddressInput.getText()); 
                        partners.remove(i);
                        partners.add(i, partner);
                        fileSocio.writeFile(partners);
                        this.dispose();
                    }
                    break;
                }
            }
        } 
        catch (IOException ex) {
 
        }
    }//GEN-LAST:event_editAcceptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartnerEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartnerEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartnerEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartnerEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartnerEdit("","","","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JToggleButton editAcceptButton;
    private javax.swing.JTextField editAddressInput;
    private javax.swing.JToggleButton editCancelButton;
    private javax.swing.JTextField editDniInput;
    private javax.swing.JTextField editLastnameInput;
    private javax.swing.JTextField editNameInput;
    private javax.swing.JLabel editNameLabel;
    private javax.swing.JTextField editNumSocioInput;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}